- name: install lora-app-server
  package:
    name: lora-app-server
    state: latest

- name: copy configuration
  template:
    src: lora-app-server.toml.j2
    dest: "{{ lora_appserver_configlocation }}{{ lora_appserver_name }}.toml"
    owner: "{{ lora_appserver_user }}"
    group: "{{ lora_appserver_user }}"
    mode: 0640
  notify:
  - restart lora-app-server

#- name: add nginx proxy
#  template:
#    src: lora-app-server.nginx.j2
#    dest: /etc/nginx/sites-enabled/lora-app-server
#  notify:
#    - reload nginx

- name: start lora-app-server on boot
  service:
    name: lora-app-server
    enabled: yes
    state: started
