- name: import LoRa Server gpg key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: {{ lora_apt_key_id }}
  notify: update apt cache

- name: add LoRa Server deb repository
  apt_repository:
    repo: {{ lora_apt_repository }}
    state: present
  notify: update apt cache

- name: remove deprecated(2.x) deb repository
  apt_repository:
    repo: deb https://artifacts.loraserver.io/packages/2.x/deb stable main
    state: absent
  notify: update apt cache

- name: run handlers now
  meta: flush_handlers

- name: install packages
  package:
    name:
    - apt-transport-https
    - libcap2-bin
