- name: install loraserver
  package:
    name: loraserver
    state: latest

- name: copy configuration
  template:
    src: loraserver.toml.j2
    dest: "{{ lora_networkserver_configlocation }}{{ lora_networkserver_name }}.toml"
    owner: "{{ lora_networkserver_user }}"
    group: "{{ lora_networkserver_user }}"
    mode: 0640
  notify:
  - restart loraserver

- name: start loraserver on boot
  service:
    name: loraserver
    enabled: yes
    state: started
